---
title: "R Notebook"
output: html_notebook
---

Load in the required libraries.

```{r}
library(ChannelAttribution)
library(reshape)
library(reshape2)
library(ggplot2)
library(dplyr)
```

```{r}
data <- read.csv("all_sessions_sample.csv")
```


```{r}
ChData <- as.data.frame(data)
ChData <- ChData[order(ChData$fullVisitorId, ChData$visitId, ChData$time),]
ChDataReq <- ChData[,c("fullVisitorId", "channelGrouping", "time", "date", "visitId", "transactionRevenue", "eCommerceAction_type")]
```
 
```{r}
head(ChDataReq)
```

```{r}
ChDataSort <- ChDataReq[order(ChDataReq$fullVisitorId, ChDataReq$time),]
head(ChDataSort)
```

```{r}
ChDataSort$yearMonth <- substr(ChDataReq$date, 1, 6)
head(ChDataSort)
```

```{r}
ChDataSortJul2017 <- ChDataSort[ChDataSort$yearMonth == 201707,]
head(ChDataSortJul2017)
```

```{r}
ChDataSortJul2017 %>% count(ChDataSortJul2017$fullVisitorId)
```


```{r}
path <- c()
path_count <- 1
occurance <- c()
occurance_count <- 1
transaction <- c()
transaction_count <- 1
total_null <- vector(mode = "logical", length = 4432)

for(i in 2:148087)
{
  if(i-1 < 2){
    path <- ChDataSortJul2017$channelGrouping[i-1]
    occurance <- 1
    if(is.na(ChDataSortJul2017$transactionRevenue[i-1])){
      transaction <- 0
    } else  {
    transaction <- 1
    }
  }
  
  if(ChDataSortJul2017$fullVisitorId[i] != ChDataSortJul2017$fullVisitorId[i-1]){
    path <- c(path, ChDataSortJul2017$channelGrouping[i])
    path_count <- path_count + 1
    occurance_count <- occurance_count + 1
    occurance[occurance_count] <- 1
    transaction_count <- transaction_count + 1
    transaction[transaction_count] <- 0
  }
  else if(ChDataSortJul2017$fullVisitorId[i] == ChDataSortJul2017$fullVisitorId[i-1] && path_count > 1){
    path[path_count] <- paste(path[path_count], ChDataSortJul2017$channelGrouping[i], sep = " > ")
    if(is.na(ChDataSortJul2017$transactionRevenue[i])){
      transaction[transaction_count] <- 0
      } else  {
      transaction[transaction_count] <- 1
      }
    }
  else if(ChDataSortJul2017$fullVisitorId[i] == ChDataSortJul2017$fullVisitorId[i-1] && path_count == 1){
    path <- paste(path, ChDataSortJul2017$channelGrouping[i], sep = " > ")
    if(is.na(ChDataSortJul2017$transactionRevenue[i])){
      transaction[transaction_count] <- 0
      } else  {
      transaction[transaction_count] <- 1
      }
    }
}
for(i in 1:4432){
  total_null[i] <- occurance[i] - transaction[i]
}

print("Done")
```

